#!/usr/bin/env python3
"""
Phase 1: Build EN→CN terminology glossary from the two paired Excel workbooks.

Usage:
    python scripts/build_glossary.py \
        --cn 术语对照_中文.xlsx \
        --en 术语对照_英文.xlsx \
        --output references/术语对照.md

Reads ALL columns from each file (especially columns for prerequisites, remarks, etc.),
pairs them row-by-row (rows 2..177, 1:1 alignment), and writes a comprehensive glossary.
"""

import argparse
import re
import sys

try:
    import openpyxl
except ImportError:
    print("Error: openpyxl is required. Install with: pip install openpyxl", file=sys.stderr)
    sys.exit(1)


# Columns to extract for translation
COLUMNS_TO_EXTRACT = [
    (3, "Task Name"),      # 任务名称
    (7, "Prerequisite"),   # 前提条件
    (8, "RMKS"),          # 备注
    (9, "Paperwork"),     # 文件状态
    (14, "Reason"),       # 使用特定飞机原因
    (15, "Additional"),   # 额外需求
]


def load_all_columns(path):
    """Load specified columns from an Excel workbook. Returns dict of (col_idx, col_name) -> list of texts."""
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active
    result = {}

    for col_idx, col_name in COLUMNS_TO_EXTRACT:
        rows = []
        for r in range(2, ws.max_row + 1):
            val = ws.cell(r, col_idx).value
            text = str(val).strip() if val is not None else ""
            if text:
                rows.append((r, text))
        result[(col_idx, col_name)] = rows

    wb.close()
    return result


def build_comprehensive_glossary(cn_data, en_data):
    """Build glossary from all columns."""
    glossary = {}  # EN_lower -> [(EN, CN, column_name)]

    # Process each column
    for (col_idx, col_name) in COLUMNS_TO_EXTRACT:
        cn_rows = cn_data.get((col_idx, col_name), [])
        en_rows = en_data.get((col_idx, col_name), [])

        for (cn_row, cn_text), (en_row, en_text) in zip(cn_rows, en_rows):
            en_key = en_text.lower().strip()
            cn_key = cn_text.strip()

            if not en_key or not cn_key:
                continue

            if en_key not in glossary:
                glossary[en_key] = []

            # Check if this pair already exists
            if not any(p[0] == en_text.strip() and p[1] == cn_key and p[2] == col_name
                      for p in glossary[en_key]):
                glossary[en_key].append((en_text.strip(), cn_key, col_name))

    return glossary


def write_glossary_md(glossary, output_path):
    """Write the comprehensive glossary as a markdown file."""
    sorted_entries = sorted(glossary.items(), key=lambda x: x[0])

    lines = []
    lines.append("# 术语对照 / Terminology Glossary")
    lines.append("")
    lines.append("> Auto-generated by build_glossary.py from the paired 术语对照 Excel workbooks.")
    lines.append("> Extracts all columns: Task Names, Prerequisites, Remarks, Paperwork Status, Reason, Additional Req.")
    lines.append("")
    lines.append(f"*Total entries: {len(sorted_entries)}*")
    lines.append("")

    # Group by column
    for col_idx, col_name in COLUMNS_TO_EXTRACT:
        lines.append(f"## {col_name} Translations")
        lines.append("")
        lines.append("| EN | CN |")
        lines.append("|---|---|")

        col_entries = []
        for en_key, pairs in sorted_entries:
            for en_text, cn_text, source_col in pairs:
                if source_col == col_name:
                    col_entries.append((en_text, cn_text))

        # Sort by English text
        col_entries.sort(key=lambda x: x[0].lower())

        for en_text, cn_text in col_entries:
            en_escaped = en_text.replace("|", "\\|")
            cn_escaped = cn_text.replace("|", "\\|")
            lines.append(f"| {en_escaped} | {cn_escaped} |")

        if not col_entries:
            lines.append("| (none) | (none) |")

        lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Glossary written to: {output_path}")
    print(f"Total entries: {len(sorted_entries)}")


def main():
    parser = argparse.ArgumentParser(description="Build EN→CN glossary from paired Excel workbooks")
    parser.add_argument("--cn", required=True, help="Path to 术语对照_中文.xlsx")
    parser.add_argument("--en", required=True, help="Path to 术语对照_英文.xlsx")
    parser.add_argument("--output", required=True, help="Output markdown path")
    args = parser.parse_args()

    print("Loading Chinese terminology data...")
    cn_data = load_all_columns(args.cn)
    print(f"  Loaded columns from CN file")

    print("Loading English terminology data...")
    en_data = load_all_columns(args.en)
    print(f"  Loaded columns from EN file")

    glossary = build_comprehensive_glossary(cn_data, en_data)
    write_glossary_md(glossary, args.output)


if __name__ == "__main__":
    main()
